import "./globals.css";
import Link from "next/link";  
import { getServerSession } from "next-auth/next"; // 서버에서 세션 정보를 가져옴.
import { authOptions } from "@/lib/auth"; // authOptions를 가져옵니다.
import { cookies } from "next/headers"; //2-1. 브라우저 쿠키데이터 사용하기(서버 & 클라이언트 동시 사용))
import LoginBtn from "./LoginBtn";
import LogoutBtn from "./LogoutBtn";
import DarkMode from "./DarkMode";
import SessionProvider from "./SessionProvider";
import QueryProvider from "./QueryProvider"; //3-1.

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions); //1-1 서버에서 세션 정보를 가져옵니다.
  //console.log('세션출력' + JSON.stringify(session)); //1-2. 세션 출력
  const cookieStore = await cookies();
  let cookie = cookieStore.get('mode'); //2-1. 쿠키 데이터 가져오기(테스트)
    //서버컴포넌트에선 cookies() 쓰면 쿠키값 출력이 쉽게 가능
  return (
    <html lang="en">
      <body className={ 
        cookie != undefined && cookie.value == 'dark'//클래스명을 'dark-mode'로 저장
          ? 'dark-mode'
          : ''
      }>
        <QueryProvider>
          <SessionProvider session={session}>
            <div className="navbar">
              <div>
                {" "}
                <Link href="/" className="logo">
                  BSSM게시판
                </Link>
                <Link href="/list">목록보기</Link>
                <Link href="/write">글작성</Link>
                <Link href="/register">회원가입</Link>
              </div>
              <div>
                <DarkMode/>
                {session ? (
                  <span>
                    {session.user.name} <LogoutBtn />{" "}
                  </span>
                ) : (
                  <LoginBtn />
                )}
              </div>
            </div>

            {children}
          </SessionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
