// app/layout.js
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/" className="link">
            홈
          </Link>
          <Link href="/list" className="link">
            목록
          </Link>
          <Link href="/write" className="link">
            글 작성
          </Link>
          <Link href="/about" className="link">
            About
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
