import "./globals.css";
import LoginBtn from "./Login.js";
import Logout from "./Logout";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route"; //1-1. import

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  if (session) {
    console.log(JSON.stringify(session));
  }
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">
            BSSM board
          </Link>
          <Link href="/list">글목록</Link>
          {session ? <Logout /> : <LoginBtn />}
        </div>
        {children}
        {session && (
          <div>
            <img src={session.user.image}></img>
            <div>{session.user.name}</div>
          </div>
        )}
      </body>
    </html>
  );
}
